import mongoose from "mongoose";
import dotenv from "dotenv";
import Workout from "../models/Workout.js";

dotenv.config();

const workouts = [
  // CHEST
  {
    name: "Barbell Bench Press",
    muscleGroup: "chest",
    workoutType: "Compound",
    sets: 4,
    reps: "8-10",
    difficulty: "intermediate",
    equipment: "barbell",
    instructions:
      "Keep shoulder blades retracted, feet flat. Bar touches mid-chest.",
  },
  {
    name: "Incline Dumbbell Press",
    muscleGroup: "chest",
    workoutType: "Compound",
    sets: 4,
    reps: "10-12",
    difficulty: "beginner",
    equipment: "dumbbell",
    instructions: "Set bench 30-45°. Targets upper chest.",
  },
  {
    name: "Decline Bench Press",
    muscleGroup: "chest",
    workoutType: "Compound",
    sets: 3,
    reps: "10-12",
    difficulty: "intermediate",
    equipment: "barbell",
    instructions: "Targets lower chest. Keep head higher than hips.",
  },
  {
    name: "Dumbbell Flyes",
    muscleGroup: "chest",
    workoutType: "Isolation",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "dumbbell",
    instructions: "Slight bend in elbows. Stretch at bottom, squeeze at top.",
  },
  {
    name: "Cable Crossover",
    muscleGroup: "chest",
    workoutType: "Cable",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "cable",
    instructions: "Keep core tight. Great finisher for chest pump.",
  },
  {
    name: "Pec Deck Machine",
    muscleGroup: "chest",
    workoutType: "Isolation",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "machine",
    instructions: "Fixed path isolates chest safely.",
  },
  {
    name: "Push-ups",
    muscleGroup: "chest",
    workoutType: "Bodyweight",
    sets: 4,
    reps: "15-20",
    difficulty: "beginner",
    equipment: "bodyweight",
    instructions: "Hands slightly wider than shoulders. Full range of motion.",
  },
  {
    name: "Chest Dips",
    muscleGroup: "chest",
    workoutType: "Bodyweight",
    sets: 3,
    reps: "10-15",
    difficulty: "intermediate",
    equipment: "bodyweight",
    instructions: "Lean forward slightly to target chest over triceps.",
  },

  // BACK
  {
    name: "Deadlift",
    muscleGroup: "back",
    workoutType: "Compound",
    sets: 4,
    reps: "5-6",
    difficulty: "advanced",
    equipment: "barbell",
    instructions: "Neutral spine. Hinge at hips, drive through heels.",
  },
  {
    name: "Barbell Bent-over Row",
    muscleGroup: "back",
    workoutType: "Compound",
    sets: 4,
    reps: "8-10",
    difficulty: "intermediate",
    equipment: "barbell",
    instructions: "Hinge to 45°, pull bar to lower chest. Keep back flat.",
  },
  {
    name: "Pull-ups",
    muscleGroup: "back",
    workoutType: "Bodyweight",
    sets: 4,
    reps: "6-10",
    difficulty: "intermediate",
    equipment: "bodyweight",
    instructions: "Full dead hang at bottom. Chin over bar at top.",
  },
  {
    name: "Lat Pulldown",
    muscleGroup: "back",
    workoutType: "Cable",
    sets: 4,
    reps: "10-12",
    difficulty: "beginner",
    equipment: "cable",
    instructions: "Pull to upper chest. Lean back slightly.",
  },
  {
    name: "Seated Cable Row",
    muscleGroup: "back",
    workoutType: "Cable",
    sets: 3,
    reps: "10-12",
    difficulty: "beginner",
    equipment: "cable",
    instructions: "Squeeze shoulder blades together at end of each rep.",
  },
  {
    name: "Single-arm Dumbbell Row",
    muscleGroup: "back",
    workoutType: "Isolation",
    sets: 3,
    reps: "10-12",
    difficulty: "beginner",
    equipment: "dumbbell",
    instructions: "Brace on bench, row to hip. Full stretch at bottom.",
  },
  {
    name: "T-bar Row",
    muscleGroup: "back",
    workoutType: "Compound",
    sets: 3,
    reps: "8-10",
    difficulty: "intermediate",
    equipment: "barbell",
    instructions: "Great for mid-back thickness. Keep chest on pad.",
  },
  {
    name: "Face Pulls",
    muscleGroup: "back",
    workoutType: "Cable",
    sets: 3,
    reps: "15-20",
    difficulty: "beginner",
    equipment: "cable",
    instructions:
      "Pull to forehead level, elbows high. Essential for shoulder health.",
  },

  // BICEPS
  {
    name: "Barbell Curl",
    muscleGroup: "biceps",
    workoutType: "Barbell",
    sets: 4,
    reps: "8-10",
    difficulty: "beginner",
    equipment: "barbell",
    instructions: "Keep elbows pinned to sides. Avoid swinging torso.",
  },
  {
    name: "Incline Dumbbell Curl",
    muscleGroup: "biceps",
    workoutType: "Dumbbell",
    sets: 3,
    reps: "10-12",
    difficulty: "beginner",
    equipment: "dumbbell",
    instructions: "Sit back on incline bench. Full stretch at the bottom.",
  },
  {
    name: "Hammer Curl",
    muscleGroup: "biceps",
    workoutType: "Dumbbell",
    sets: 3,
    reps: "10-12",
    difficulty: "beginner",
    equipment: "dumbbell",
    instructions: "Neutral grip hits brachialis. Adds width to arms.",
  },
  {
    name: "Concentration Curl",
    muscleGroup: "biceps",
    workoutType: "Dumbbell",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "dumbbell",
    instructions: "Elbow on inner thigh. Great mind-muscle connection.",
  },
  {
    name: "Cable Curl",
    muscleGroup: "biceps",
    workoutType: "Cable",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "cable",
    instructions: "Constant tension throughout. Great finisher.",
  },
  {
    name: "Spider Curl",
    muscleGroup: "biceps",
    workoutType: "Barbell",
    sets: 3,
    reps: "10-12",
    difficulty: "intermediate",
    equipment: "barbell",
    instructions: "Chest on incline bench facing down. Eliminates cheating.",
  },
  {
    name: "Preacher Curl",
    muscleGroup: "biceps",
    workoutType: "Machine",
    sets: 3,
    reps: "10-12",
    difficulty: "beginner",
    equipment: "machine",
    instructions: "Lock elbows on pad. Controlled negative.",
  },
  {
    name: "Zottman Curl",
    muscleGroup: "biceps",
    workoutType: "Dumbbell",
    sets: 3,
    reps: "10-12",
    difficulty: "intermediate",
    equipment: "dumbbell",
    instructions: "Curl up supinated, rotate to pronated on the way down.",
  },

  // TRICEPS
  {
    name: "Close-grip Bench Press",
    muscleGroup: "triceps",
    workoutType: "Compound",
    sets: 4,
    reps: "8-10",
    difficulty: "intermediate",
    equipment: "barbell",
    instructions: "Hands shoulder-width. Elbows close to body.",
  },
  {
    name: "Skull Crushers",
    muscleGroup: "triceps",
    workoutType: "Isolation",
    sets: 3,
    reps: "10-12",
    difficulty: "intermediate",
    equipment: "barbell",
    instructions: "Lower bar to forehead. Full stretch of long head.",
  },
  {
    name: "Tricep Pushdown",
    muscleGroup: "triceps",
    workoutType: "Cable",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "cable",
    instructions: "Keep elbows locked at sides. Squeeze at full extension.",
  },
  {
    name: "Overhead Tricep Extension",
    muscleGroup: "triceps",
    workoutType: "Cable",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "cable",
    instructions: "Best exercise for long head. Keep elbows close to head.",
  },
  {
    name: "Tricep Dips",
    muscleGroup: "triceps",
    workoutType: "Bodyweight",
    sets: 3,
    reps: "10-15",
    difficulty: "beginner",
    equipment: "bodyweight",
    instructions: "Stay upright to target triceps over chest.",
  },
  {
    name: "Diamond Push-ups",
    muscleGroup: "triceps",
    workoutType: "Bodyweight",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "bodyweight",
    instructions: "Hands form a diamond. Elbows track back, not out.",
  },
  {
    name: "Dumbbell Kickback",
    muscleGroup: "triceps",
    workoutType: "Isolation",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "dumbbell",
    instructions: "Hinge forward, upper arm parallel to floor. Extend fully.",
  },
  {
    name: "JM Press",
    muscleGroup: "triceps",
    workoutType: "Compound",
    sets: 3,
    reps: "8-10",
    difficulty: "advanced",
    equipment: "barbell",
    instructions: "Hybrid skull crusher and close-grip press.",
  },

  // SHOULDERS
  {
    name: "Overhead Press (Barbell)",
    muscleGroup: "shoulders",
    workoutType: "Compound",
    sets: 4,
    reps: "6-8",
    difficulty: "intermediate",
    equipment: "barbell",
    instructions: "Core tight, bar path straight up. Do not arch lower back.",
  },
  {
    name: "Dumbbell Shoulder Press",
    muscleGroup: "shoulders",
    workoutType: "Compound",
    sets: 4,
    reps: "10-12",
    difficulty: "beginner",
    equipment: "dumbbell",
    instructions: "More range of motion than barbell.",
  },
  {
    name: "Lateral Raises",
    muscleGroup: "shoulders",
    workoutType: "Isolation",
    sets: 4,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "dumbbell",
    instructions: "Lead with elbows. Pinky slightly higher than thumb.",
  },
  {
    name: "Front Raises",
    muscleGroup: "shoulders",
    workoutType: "Isolation",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "dumbbell",
    instructions: "Alternate arms or both together. Avoid swinging.",
  },
  {
    name: "Rear Delt Flyes",
    muscleGroup: "shoulders",
    workoutType: "Isolation",
    sets: 3,
    reps: "15-20",
    difficulty: "beginner",
    equipment: "dumbbell",
    instructions: "Hinge forward 90°. Often undertrained — prioritise this.",
  },
  {
    name: "Arnold Press",
    muscleGroup: "shoulders",
    workoutType: "Compound",
    sets: 3,
    reps: "10-12",
    difficulty: "intermediate",
    equipment: "dumbbell",
    instructions: "Rotation hits all three delt heads in one movement.",
  },
  {
    name: "Cable Lateral Raise",
    muscleGroup: "shoulders",
    workoutType: "Cable",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "cable",
    instructions: "Cross-body cable gives better tension at the bottom.",
  },
  {
    name: "Machine Shoulder Press",
    muscleGroup: "shoulders",
    workoutType: "Machine",
    sets: 3,
    reps: "10-12",
    difficulty: "beginner",
    equipment: "machine",
    instructions: "Guided path is safer for beginners.",
  },

  // LEGS
  {
    name: "Barbell Squat",
    muscleGroup: "legs",
    workoutType: "Compound",
    sets: 4,
    reps: "6-8",
    difficulty: "advanced",
    equipment: "barbell",
    instructions: "Knees track over toes. Depth below parallel.",
  },
  {
    name: "Romanian Deadlift",
    muscleGroup: "legs",
    workoutType: "Compound",
    sets: 4,
    reps: "8-10",
    difficulty: "intermediate",
    equipment: "barbell",
    instructions: "Hinge at hips, soft bend in knees. Best hamstring exercise.",
  },
  {
    name: "Leg Press",
    muscleGroup: "legs",
    workoutType: "Machine",
    sets: 4,
    reps: "10-12",
    difficulty: "beginner",
    equipment: "machine",
    instructions: "Feet high and wide for glutes. Low and narrow for quads.",
  },
  {
    name: "Bulgarian Split Squat",
    muscleGroup: "legs",
    workoutType: "Compound",
    sets: 3,
    reps: "10-12",
    difficulty: "intermediate",
    equipment: "dumbbell",
    instructions: "Rear foot elevated. Most effective single-leg exercise.",
  },
  {
    name: "Leg Extension",
    muscleGroup: "legs",
    workoutType: "Isolation",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "machine",
    instructions: "Isolates quads. Pause at top. Controlled movement.",
  },
  {
    name: "Leg Curl",
    muscleGroup: "legs",
    workoutType: "Isolation",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "machine",
    instructions: "Full stretch at bottom is key for hamstring growth.",
  },
  {
    name: "Calf Raises",
    muscleGroup: "legs",
    workoutType: "Isolation",
    sets: 4,
    reps: "15-20",
    difficulty: "beginner",
    equipment: "machine",
    instructions: "Full range of motion. Slow and controlled.",
  },
  {
    name: "Walking Lunges",
    muscleGroup: "legs",
    workoutType: "Bodyweight",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "bodyweight",
    instructions: "Step long enough so front knee stays behind toes.",
  },

  // ABS
  {
    name: "Cable Crunch",
    muscleGroup: "abs",
    workoutType: "Cable",
    sets: 4,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "cable",
    instructions: "Round the spine — do not pull with arms.",
  },
  {
    name: "Hanging Leg Raise",
    muscleGroup: "abs",
    workoutType: "Bodyweight",
    sets: 4,
    reps: "10-15",
    difficulty: "intermediate",
    equipment: "bodyweight",
    instructions: "Full hang. Raise legs to 90°. Avoid swinging.",
  },
  {
    name: "Plank",
    muscleGroup: "abs",
    workoutType: "Bodyweight",
    sets: 3,
    reps: "45-60s",
    difficulty: "beginner",
    equipment: "bodyweight",
    instructions: "Do not let hips sag or pike up.",
  },
  {
    name: "Ab Wheel Rollout",
    muscleGroup: "abs",
    workoutType: "Bodyweight",
    sets: 3,
    reps: "8-12",
    difficulty: "advanced",
    equipment: "bodyweight",
    instructions: "Start on knees. Most effective abs exercise once mastered.",
  },
  {
    name: "Crunch",
    muscleGroup: "abs",
    workoutType: "Bodyweight",
    sets: 3,
    reps: "15-20",
    difficulty: "beginner",
    equipment: "bodyweight",
    instructions: "Lift shoulder blades only — not a full sit-up.",
  },
  {
    name: "Decline Sit-up",
    muscleGroup: "abs",
    workoutType: "Weighted",
    sets: 3,
    reps: "12-15",
    difficulty: "beginner",
    equipment: "machine",
    instructions: "Add weight plate on chest for progressive overload.",
  },
  {
    name: "Russian Twist",
    muscleGroup: "abs",
    workoutType: "Weighted",
    sets: 3,
    reps: "20-30",
    difficulty: "beginner",
    equipment: "dumbbell",
    instructions: "Hold weight, rotate fully side to side. Great for obliques.",
  },
  {
    name: "Dragon Flag",
    muscleGroup: "abs",
    workoutType: "Bodyweight",
    sets: 3,
    reps: "5-8",
    difficulty: "advanced",
    equipment: "bodyweight",
    instructions: "Advanced full-body core movement. Start with negatives.",
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    await Workout.deleteMany({});
    console.log("Cleared existing workouts");

    await Workout.insertMany(workouts);
    console.log(`Seeded ${workouts.length} exercises successfully`);

    process.exit(0);
  } catch (err) {
    console.error("Seed failed:", err.message);
    process.exit(1);
  }
};

seed();
